#!/bin/bash

set -e

: ${SERVER_DOMAIN:="example.server.com"}
: ${CLIENT_DOMAIN:="example.client.com"}

cat > my-openssl.cnf << EOF
[ ca ]
default_ca = CA_default
[ CA_default ]
x509_extensions = usr_cert
[ req ]
default_bits        = 2048
default_md          = sha256
default_keyfile     = privkey.pem
distinguished_name  = req_distinguished_name
attributes          = req_attributes
x509_extensions     = v3_ca
string_mask         = utf8only
[ req_distinguished_name ]
[ req_attributes ]
[ usr_cert ]
basicConstraints       = CA:FALSE
nsComment              = "OpenSSL Generated Certificate"
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid,issuer
[ v3_ca ]
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid:always,issuer
basicConstraints       = CA:true
EOF


# Generate CA private key
openssl genrsa -out ca.key 2048
# Generate CA certificate
openssl req -x509 -new -nodes -key ca.key -subj "/CN=FRP Root CA" -days 5000 -out ca.crt


# Generate server private key
openssl genrsa -out server.key 2048

# Generate server certificate signing request
openssl req -new -sha256 -key server.key \
    -subj "/CN=${SERVER_DOMAIN}" \
    -reqexts SAN \
    -config <(cat my-openssl.cnf <(printf "\n[SAN]\nsubjectAltName=DNS:${SERVER_DOMAIN},DNS:localhost,IP:127.0.0.1")) \
    -out server.csr

# Sign server certificate using CA
openssl x509 -req -days 3650 -sha256 \
	-in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
	-extfile <(printf "subjectAltName=DNS:${SERVER_DOMAIN},DNS:localhost,IP:127.0.0.1") \
	-out server.crt


# Generate client private key
openssl genrsa -out client.key 2048
# Generate client certificate signing request
openssl req -new -sha256 -key client.key \
    -subj "/CN=${CLIENT_DOMAIN}" \
    -reqexts SAN \
    -config <(cat my-openssl.cnf <(printf "\n[SAN]\nsubjectAltName=DNS:${CLIENT_DOMAIN}")) \
    -out client.csr
# Sign client certificate using CA
openssl x509 -req -days 3650 -sha256 \
    -in client.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
	-extfile <(printf "subjectAltName=DNS:${CLIENT_DOMAIN}") \
	-out client.crt


rm my-openssl.cnf server.csr client.csr ca.srl 2>/dev/null
